import React from 'react';
import { ShieldCheck, Zap, Coins, Bot, Users, Globe, Layout, Cpu } from 'lucide-react';

const About = () => {
  return (
    <div className="min-h-screen text-white pb-20 px-4 sm:px-6 lg:px-8 mt-4 md:mt-10 overflow-auto no-scrollbar">
      {/* Header Section */}
      <div className="max-w-4xl mx-auto text-center mb-16">
        <h1 className="text-4xl md:text-6xl font-extrabold mb-6 tracking-tight">
          Welcome to <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-600">VarTul</span>
        </h1>
        <p className="text-lg md:text-xl text-gray-400 font-light max-w-2xl mx-auto leading-relaxed">
          The next-generation social platform designed to truly reward engagement. 
          We merge the familiarity of everyday social media with the powerful economies of Web3 and Machine Learning.
        </p>
      </div>

      {/* Grid Features */}
      <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        
        {/* Web3 & Solana */}
        <div className="bg-white/5 border border-white/10 backdrop-blur-lg p-8 rounded-3xl shadow-xl hover:bg-white/10 transition duration-300 group">
          <div className="w-14 h-14 bg-blue-500/20 text-blue-400 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <Coins size={28} />
          </div>
          <h3 className="text-2xl font-bold mb-3">On-Chain Rewards</h3>
          <p className="text-gray-400 leading-relaxed text-sm">
            Powered by the incredibly fast Solana Blockchain. Connect your Phantom or Backpack wallet to stake our native <span className="text-white font-semibold flex items-center gap-1 inline-flex"><Zap size={14} className="text-yellow-400"/>TWT (Vartul Watch Token)</span>. Watch reels, complete milestones, and earn real yield through our sophisticated Proof-of-Engagement Anchor smart contracts.
          </p>
        </div>

        {/* ML & Bot Detection */}
        <div className="bg-white/5 border border-white/10 backdrop-blur-lg p-8 rounded-3xl shadow-xl hover:bg-white/10 transition duration-300 group">
          <div className="w-14 h-14 bg-purple-500/20 text-purple-400 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <Bot size={28} />
          </div>
          <h3 className="text-2xl font-bold mb-3">AI Bot Defense</h3>
          <p className="text-gray-400 leading-relaxed text-sm">
            Rewards are meant for real humans. Our localized Python/Flask Machine Learning architecture deeply analyzes feed interactions, instantly detecting and flagging bot behavior, guaranteeing a fair and organic user experience across the ecosystem.
          </p>
        </div>

        {/* MERN Architecture */}
        <div className="bg-white/5 border border-white/10 backdrop-blur-lg p-8 rounded-3xl shadow-xl hover:bg-white/10 transition duration-300 group">
          <div className="w-14 h-14 bg-green-500/20 text-green-400 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
            <Layout size={28} />
          </div>
          <h3 className="text-2xl font-bold mb-3">Flawless UI/UX</h3>
          <p className="text-gray-400 leading-relaxed text-sm">
            Built on a robust MERN (MongoDB, Express, React, Node.js) stack supercharged with Vite. Enjoy glassmorphic aesthetics, ultra-smooth scrolling reels, real-time WebSocket messaging, and decentralized media delivery through Pinata IPFS.
          </p>
        </div>

      </div>

      {/* Philosophy Section */}
      <div className="max-w-4xl mx-auto mt-20 pt-16 border-t border-white/10">
        <h2 className="text-3xl font-bold text-center mb-10">Why We Built VarTul</h2>
        <div className="space-y-8">
          <div className="flex gap-6 items-start">
            <div className="bg-gray-800 p-3 rounded-xl border border-gray-700">
              <Users className="text-blue-400" size={24} />
            </div>
            <div>
              <h4 className="text-xl font-semibold mb-2">Empowering Creators</h4>
              <p className="text-gray-400 text-sm leading-relaxed">
                Traditional social media platforms pocket the vast majority of ad revenue generated by user interaction. VarTul changes the paradigm by utilizing liquidity pools to redistribute value back to the creators producing the content and the active users viewing it.
              </p>
            </div>
          </div>
          <div className="flex gap-6 items-start">
            <div className="bg-gray-800 p-3 rounded-xl border border-gray-700">
              <ShieldCheck className="text-green-400" size={24} />
            </div>
            <div>
              <h4 className="text-xl font-semibold mb-2">Transparent & Trustless</h4>
              <p className="text-gray-400 text-sm leading-relaxed">
                By offloading engagement milestones to immutable Solana smart contracts, you no longer have to blindly trust an algorithm. Yield and token distribution rules are written in Rust, publicly verifiable, and secured natively by the blockchain consensus.
              </p>
            </div>
          </div>
          <div className="flex gap-6 items-start">
            <div className="bg-gray-800 p-3 rounded-xl border border-gray-700">
              <Globe className="text-indigo-400" size={24} />
            </div>
            <div>
              <h4 className="text-xl font-semibold mb-2">Decentralized Content</h4>
              <p className="text-gray-400 text-sm leading-relaxed">
                Say goodbye to arbitrary platform takedowns. VarTul utilizes Pinata (IPFS) ensuring that content hashes and post asset locations exist across a decentralized array of nodes rather than sitting idle on a single monolithic server.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="text-center mt-20 text-gray-500 text-sm pb-10">
        <p>© 2025 VarTul Platform. Built with passion from Manipal.</p>
        <p className="mt-2 flex items-center justify-center gap-2">
          <Cpu size={14} className="text-gray-400" />
          Systems operational: Solana Devnet & Vartul Main Node.
        </p>
      </div>

    </div>
  );
};

export default About;